Add files via upload
Hard6969/Hard6969 pull request #4
Opened 2023-09-29 19:11 UTC by Hard6969

2023-09-30 11:27 UTC, Yefremovigor commented on index.html
> +    <meta charset="utf-8">
Это оставляем в head так валиднее

2023-09-30 11:30 UTC, Yefremovigor commented on index.html
> +    <title>Заголовок сайта</title>
в head надо закинуть еще:
```
<meta charset="UTF-8" />
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
```
это все перед тайтлом оно нужно для адаптивной верстки потом
emmit в редакторах кода хорошо разворачивает базовую настройку страницы если все стереть, поставить `!` и нажать таб.
Но это на будущее

2023-09-30 11:33 UTC, Yefremovigor commented on index.html
> +    </H1>
Хорошо что логотип не в навигации это правилнь!
Но логотип не H1 это картинка завернутая в ссылку, примерно так.
```
<a class="page-header__logo logo" href="/">
      <div class="logo__icon"><img src="./images/logo.svg" alt="Логотип Мой Блог" /></div>
      <span class="logo__text">Мой Блог</span>
</a>
```

2023-09-30 11:34 UTC, Yefremovigor commented on index.html
> +<header>
У всего вешай классы уже сейчас, потом будем использовать БЭМ-нейминг, там это вообще как закон, стоит начать привыкать...

2023-09-30 11:35 UTC, Yefremovigor commented on index.html
> +        <a href="index.html" class="nav_button"> <h2>Мой блог</h2> </a>
Лучше ссылку ставить как / ели это на главную, но тут пофиг просто на будущее

2023-09-30 11:37 UTC, Yefremovigor commented on index.html
> +    </H1>
Лучше везде писать все теги со строчно буквы, тк потом в JS с заглавной пишут собственные компоненты, они выглядят как обычные теги и только так отличимы на первый взгляд, ну еще по названию...

2023-09-30 11:40 UTC, Yefremovigor commented on index.html
> +        <div class="search">
для обозначения блока поиска появился семантический тэг search (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/search)

Поддержка пока так себе, но можно воспользоваться пока лайфхаком и прописать так:

```
<search role="search">
   ...
</search>
```

то есть `search` вместо `div`

Скажу честно, сам узна об этом только вчера, что он появился =)

2023-09-30 11:44 UTC, Yefremovigor commented on index.html
> +            <form>
В form надо прописать action и method
action - адрес скрипта обработчика, method - способ отправки, для поисков и всяких фильтров товаров это всегда get что бы можно было ссылкой поделится или добавить ссылку с результатами поиска в избранное.
Для форм обратной связи, входа на сайт и будет post. Есть еще методы, они будут нужны сильно потом, можешь пока не заморачиваться в их изучении.

`action="/search" method="get"`

2023-09-30 11:47 UTC, Yefremovigor commented on index.html
> +<body class="body">
Идет 
<html> 
  <head>
     ...
  </head>
  <body>
      ...
  </body>
</html>

body с классом body - огонь, прям по БЭМу =)

2023-09-30 11:53 UTC, Yefremovigor commented on index.html
> +    <p>FRONTEND - 12 МАЯ 2024</p>
Тут нет полноценного абзаца текста, поэтому `div`,
`-` тут не нужно, это потом стилями сделаем, а вот дату надо завернуть в `time`, это очень семантично и любят поисковики +10 к SEO =)

[<time datetime="2024-05-12" class="post__date">12 мая 2024</time>](https://developer.mozilla.org/ru/docs/Web/HTML/Element/time)

2023-09-30 11:55 UTC, Yefremovigor commented on index.html
> +<h1>
Тут правильно, именно это h1, он к стати по хорошему только один на странице, в теории может быть несколько в определенных случаях, но прибежит SEOшник и будет ругиться

2023-09-30 11:57 UTC, Yefremovigor commented on index.html
> +    <pre>
`<pre>` тут не нужен потом просто настроим ширину стилями и текст перенесётся как надо

2023-09-30 12:01 UTC, Yefremovigor commented on index.html
> +    <img src="image1.svg" class="avatar" alt="Аватарка">
`alt` лучше делать осмысленным, например "Фото автора", или "Фото Наталья Васильева"

2023-09-30 12:07 UTC, Yefremovigor commented on index.html
> +    <h2 class="nickname">Наталья Васильева</h2>
Это не h2, тк не тянет на смысловой заголовок 

Хороший пример, представь статью по замене акума в ноуте:
`h1` как поменять аккумвлятор в ноуте и не спалить его
`p` со времене батераея блабла бла
`h2 `снимаем заднюю крышку
`p` обычно кришки на вента, а онизаразы, разной длинны, подготовте лист бумаги что бы сделать крту располоения винтов и в итоге иметь возмодность собрать ноут обратно....

2023-09-30 12:09 UTC, Yefremovigor commented on index.html
> +    <img src="big_image.svg" alt="Большая картинка">
`alt` -  то же самое, лучше что-то осмысленное

2023-09-30 12:18 UTC, Yefremovigor requested changes

2023-09-30 12:18 UTC, Yefremovigor commented on index.html
> +    <meta charset="utf-8">
Это оставляем в head так валиднее

2023-09-30 18:12 UTC, Hard6969 commented on index.html
> +    <title>Заголовок сайта</title>
Понял, учту на будущее

2023-09-30 18:20 UTC, Hard6969 commented on index.html
> +    </H1>
Это не логотип в данном случае, просто буква в оформлении. В общем случае  это logo.png - завернутая в div. Я под этот шаблон адаптировать пытался. Лого сайта отдельно  размещается, эт я в курсе ) Исправлю )

2023-09-30 18:21 UTC, Hard6969 commented on index.html
> +    <title>Заголовок сайта</title>
Понянтно )

2023-09-30 18:25 UTC, Hard6969 commented on index.html
> +        <a href="index.html" class="nav_button"> <h2>Мой блог</h2> </a>
Неа. Тут смысл - по ссылке перейти на главную страницу сайта. Т.е. она возвращает с любой страницы на начальную. Заглушку можно было сделать на корень - но - в данном случае - на индекс - будет целесообразнее - он является главной страницей.

2023-09-30 18:28 UTC, Hard6969 commented on index.html
> +<body class="body">
таки а зачем мудрить с именами? Класс body прописывать придется полюбому ))) Проще всего - задать сразу.

2023-09-30 18:31 UTC, Hard6969 commented on index.html
> +    <pre>
Проще было предварительно выровнять <pre>, это больше для себя, чтобы глаз не резало )

2023-09-30 18:33 UTC, Hard6969 commented on index.html
> +    <img src="image1.svg" class="avatar" alt="Аватарка">
Альт не ориентирован на конкретную личность, поэтому нейтральный. Просто обозначает элемент, который там должен быть.

2023-10-02 16:39 UTC, Hard6969 commented on index.html
> +        <div class="search">
Не знал про поиск, нашел, почитал

2023-10-02 16:39 UTC, Hard6969 commented on index.html
> +    <h2 class="nickname">Наталья Васильева</h2>
Заменил

2023-10-02 16:40 UTC, Hard6969 commented on index.html
> +    <img src="big_image.svg" alt="Большая картинка">
Заменил

2023-10-03 09:11 UTC, Yefremovigor commented on index.html
> +        В исследовании «Влияние цвета на маркетинг» (Impact of color on marketing) говорится, что использование
Impact of color on marketing - это ссылка кстати

2023-10-03 09:11 UTC, Yefremovigor commented on index.html
> +    </H1>
Не надо адаптировать, просто картинка в ссылке на "/"
ну и да, там не png, а svg, но это мелочи

по ссылки на "/", так сработает на главную всегда, нк важно на чем сайт.
index.php и index.html это то что по умолчанию откроется если зайти в папку или на главную, по сути в корневую папку сайта =)

2023-10-03 09:11 UTC, Yefremovigor commented on index.html
> +        <a href="index.html" class="nav_button"> <h2>Мой блог</h2> </a>
Это вот к тому что писал выше, лучше не привязываться к файлу, он может иметь любое расширение

2023-10-03 09:11 UTC, Yefremovigor commented on index.html
> +<body class="body">
Вот про эту часть не забудь плиз:
Основная часть содержимого это main, а саму статью хорошо бы завернуть в article

2023-10-03 09:11 UTC, Yefremovigor commented on index.html
> +    <img src="image1.svg" class="avatar" alt="Аватарка">
Не, альт как раз говорит про то, что на картинке, это используют люди, когда не загрузилась картинка, читалки (алиса и помощники для слабовидящих) поисковые боты, что бы лучше понять что на картике и показать в результатах поиска

Почитай плиз https://htmlacademy.ru/blog/html/alt-text

2023-10-05 16:24 UTC, closed without merging